import Foundation

var s = Stack<Int>()
assert(s.isEmpty())
assert(s.description == "Empty")
s.push(1)
assert(!s.isEmpty())
s.push(2)
s.push(3)
s.push(4)
assert(s.description == "TOP: 4 -> 3 -> 2 -> 1")
assert(s.peek() == 4)
assert(s.pop() == 4)
assert(s.pop() == 3)
assert(s.description == "TOP: 2 -> 1")
assert(s.pop() == 2)
assert(s.pop() == 1)
assert(s.isEmpty())
assert(s.pop() == nil)
