import Swift

let q = Queue<Int>()
assert(q.isEmpty())
assert(q.peek() == nil)
assert(q.description == "Empty")
q.add(1)
assert(!q.isEmpty())
assert(q.description == "IN:   1   :OUT")
q.add(2)
q.add(3)
q.add(4)
assert(q.description == "IN:   4 -> 3 -> 2 -> 1   :OUT")
assert(q.peek() == 1)
assert(q.remove() == 1)
assert(q.description == "IN:   4 -> 3 -> 2   :OUT")
assert(q.peek() == 2)
assert(q.remove() == 2)
assert(q.remove() == 3)
assert(q.description == "IN:   4   :OUT")
assert(q.remove() == 4)
assert(q.peek() == nil)
assert(q.isEmpty())
q.add(5)
assert(q.peek() == 5)
assert(!q.isEmpty())
q.add(6)
assert(q.description == "IN:   6 -> 5   :OUT")
